[build]
  publish = "public/"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-webmentions"

	[plugins.inputs]

	# The base url of your site (optional, default: main URL set in Netlify)
	baseUrl = "https://justin.poehnelt.com"

	# Path to the feed URL (optional, default: /feed.xml)
	feedPath = "/feed/all.xml"

	# Maximum number of feed entries to check for mentions (optional, default: 1)
	limit = 1
