packages:
  - packages/**
  - talks/**
  - apps/**
minimumReleaseAge: 2880
onlyBuiltDependencies:
  - esbuild
  - sharp
catalog:
  "@changesets/cli": ^2.29.7
  "@shikijs/markdown-it": ^3.13.0
  "@slidev/cli": ^52.2.4
  "@slidev/client": ^52.1.0
  "@slidev/parser": ^52.2.4
  "@slidev/types": ^52.1.0
  "@types/markdown-it": ^14.1.2
  "@types/qrcode": ^1.5.5
  "@unocss/core": ^66.5.1
  "@unocss/preset-web-fonts": ^66.5.1
  "@vueuse/core": ^13.9.0
  "@vueuse/integrations": ^13.9.0
  esbuild: ^0.20.2
  markdown-it: ^14.1.1
  prettier: ^3.6.2
  prettier-plugin-slidev: ^1.0.5
  qrcode: ^1.5.4
  shiki: ^3.12.2
  shiki-magic-move: ^1.0.1
  turbo: ^2.5.8
  typescript: ^5.9.2
  unocss: ^66.5.1
  vite: ^6.0.8
  vue: ^3.5.22
