Set Width 1920
Set Height 1080

Set PlaybackSpeed 1

Hide
Type "source .env"
Enter
Type "clear"
Enter
Type "gemini"
Enter
Sleep 5s
Show

Type "Create a joke about Apps Script."
Sleep 100ms
Type " Don't use any tools,"
Sleep 100ms
Type " just use what you know."

Sleep 500ms
Enter
Sleep 15s

Type "Now let's use the"
Sleep 100ms
Type " search_workspace_docs tool"
Sleep 100ms
Type " for research on a new joke."
Sleep 100ms
Type " Make sure the research is exhaustive!

Sleep 500ms
Enter
Sleep 45s

Type "/quit"
Sleep 1s
Enter
Sleep 3s
