Output ./public/jules.mp4

Set Width 1920
Set Height 1080

Set PlaybackSpeed 1.5

Hide
Type "source .env"
Enter
Type "clear"
Enter
Sleep 100ms
Show

Type "jules --help"
Enter
Sleep 10s


Type "jules remote new --repo=. --session 'Create a new slide about Google Jules for my 2025 Leveraging AI Tools in Workspace Development talk. Add it after the Jules demo video slide.'"
Enter
Sleep 200ms
Type "jules"
Enter
Sleep 60s
